
repository:
  # The name of the repository. Changing this will rename the repository
  name: LanderTek

  # A short description of the repository that will show up on GitHub
  description: "This is a modular pack of 1.25m, 1.875m, and 2.5m lander parts for Kerbal Space Program."

  # A URL with more information about the repository
  homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/207923-*/

  # A comma-separated list of topics to set on the repository
  topics: lander,tek,artwhaley,axialaerospace,kerbal,kerbalspaceprogram,ksp,ksp-mods,ksp-parts,kerbal-mods,zedk

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true
